#!/bin/bash
# Run a command as the currently active X.org server user 

seat="seat0"

# Program required check
hash loginctl 2>&- || { echo >&2 " Program \"loginctl\" not installed"; exit; }

# Input parameter(s) are executable check
hash "$1" 2>&- || \
{ echo >&2 " The specified \"$1\" is not a valid executable"; exit 1; }

# Search through active sessions for one that has the Display (X.org) value
avail_sessions=$(loginctl show-seat $seat -p Sessions| cut -d= -f2)
for session in $avail_sessions; do
  session_disp=$(loginctl show-session $session -p Display | cut -d= -f2)
  session_name=$(loginctl show-session $session -p Name    | cut -d= -f2)
  if [ -z $session_disp ]; then continue
  else break
  fi
done

# Exit if no X.org server is running
[ -z "$session_disp" ] && echo " No X.org server appears to be running" && exit 2

# Run command as X.org server user
if   [ $(whoami) = root ]; then
  XAUTHORITY=/home/$session_name/.Xauthority DISPLAY="$session_disp" \
  su -c - $session_name "$(printf "%q " "$@")" &
elif [ $(whoami) = $session_name ]; then
  eval XAUTHORITY=/home/$session_name/.Xauthority DISPLAY="$session_disp" "$@" &
else
  echo " User does not have X.org server permissions" && exit
fi
